import dotenv from "dotenv";
dotenv.config();

import { UserSeedData } from "../src/types/user.js";
import {
  getBestUserFullName,
  getEmail,
  getHashedCredentials,
} from "../src/utils/user.js";
import {
  Role,
  Gender,
  Department,
  AttendanceStatus,
  HalfDayPeriod,
} from "./generated/enums.js";
import { User } from "./generated/client.js";
import { prisma } from "../src/lib/prisma.js";

type TeamSeedData = {
  name: string;
  managerKey?: string;
  additionalMembers?: string[];
};

async function main() {
  const usersData: UserSeedData[] = [
    {
      firstName: "Arvind",
      middleName: "",
      lastName: "Palghadmal",
      employeeCode: "3001",
      role: Role.ADMIN,
      gender: Gender.MALE,
      isActive: true,
      password: process.env.ADMIN_STARTER_PASS,
      pin: process.env.ADMIN_PIN,
      email: "arvind@itviadatasolutions.com",
      dateOfJoining: new Date("2019-01-01"),
    },
    {
      firstName: "Kamlesh",
      middleName: "",
      lastName: "Thakur",
      employeeCode: "3002",
      role: Role.ADMIN,
      gender: Gender.MALE,
      isActive: true,
      password: process.env.ADMIN_STARTER_PASS,
      pin: process.env.ADMIN_PIN,
      email: "kamlesh@itviadatasolutions.com",
      dateOfJoining: new Date("2019-01-01"),
    },
    {
      firstName: "Deepa",
      middleName: "",
      lastName: "Tripathi",
      employeeCode: "3003",
      gender: Gender.FEMALE,
      role: Role.ADMIN,
      isActive: true,
      password: process.env.ADMIN_STARTER_PASS,
      pin: process.env.ADMIN_PIN,
      email: "deepa@itviadatasolutions.com",
      dateOfJoining: new Date("2019-01-01"),
    },
    {
      firstName: "Aji",
      middleName: "",
      lastName: "George",
      employeeCode: "3004",
      gender: Gender.MALE,
      role: Role.ADMIN,
      isActive: true,
      password: process.env.ADMIN_STARTER_PASS,
      pin: process.env.ADMIN_PIN,
      email: "aji@itviadatasolutions.com",
      dateOfJoining: new Date("2019-01-01"),
    },
    {
      firstName: "Deepali",
      middleName: "Pandurang",
      lastName: "Pashankar",
      gender: Gender.FEMALE,
      employeeCode: "2045",
      isActive: true,
      dateOfJoining: new Date("2021-03-30"),
    },
    {
      firstName: "Manish",
      middleName: "Sampat",
      lastName: "Chaudhari",
      gender: Gender.MALE,
      employeeCode: "2056",
      isActive: true,
      email: "manidev1216@gmail.com",
      password: process.env.EMP_STARTER_PASS,
      dateOfJoining: new Date("2021-08-11"),
    },
    {
      firstName: "Swati",
      middleName: "Shrikesh",
      lastName: "Tapkir",
      employeeCode: "2064",
      gender: Gender.FEMALE,
      isActive: true,
      email: "swati.t@itviadatasolutions.com",
      password: process.env.EMP_STARTER_PASS,
      dateOfJoining: new Date("2022-01-13"),
    },
    {
      firstName: "Gayatri",
      middleName: "",
      lastName: "More",
      employeeCode: "2086",
      gender: Gender.FEMALE,
      isActive: true,
      email: "gayatri.m@itviadatasolutions.com",
      password: process.env.EMP_STARTER_PASS,
      dateOfJoining: new Date("2023-02-01"),
    },
    {
      firstName: "Ashwini",
      middleName: "Shantaram",
      lastName: "Kamble",
      employeeCode: "2096",
      gender: Gender.FEMALE,
      isActive: true,
      email: "ashwini.k@itviadatasolutions.com",
      password: process.env.EMP_STARTER_PASS,
      dateOfJoining: new Date("2023-05-03"),
    },
    {
      firstName: "Sushil",
      middleName: "",
      lastName: "Waghmare",
      gender: Gender.MALE,
      employeeCode: "2097",
      role: Role.MANAGER,
      department: Department.SALES,
      isActive: true,
      email: "sushil@marksparksolutions.com",
      password: process.env.MANAGER_STARTER_PASS,
      dateOfJoining: new Date("2024-08-02"),
    },
    {
      firstName: "Abhijith",
      middleName: "",
      lastName: "Nair",
      gender: Gender.MALE,
      department: Department.MARKET_RESEARCH,
      employeeCode: "2098",
      isActive: true,
      dateOfJoining: new Date("2024-08-05"),
    },
    {
      firstName: "Jayesh",
      middleName: "",
      lastName: "Mali",
      gender: Gender.MALE,
      employeeCode: "2099",
      department: Department.EMAIL_MARKETING,
      isActive: true,
      dateOfJoining: new Date("2024-08-05"),
    },
    {
      firstName: "Akash",
      middleName: "",
      lastName: "Patil",
      gender: Gender.MALE,
      employeeCode: "2100",
      department: Department.EMAIL_MARKETING,
      isActive: true,
      dateOfJoining: new Date("2024-09-09"),
    },
    {
      firstName: "Rutik",
      middleName: "",
      lastName: "Devade",
      gender: Gender.MALE,
      department: Department.EMAIL_MARKETING,
      employeeCode: "2101",
      isActive: true,
      dateOfJoining: new Date("2024-09-09"),
    },
    {
      firstName: "Sumit",
      middleName: "",
      lastName: "Ingle",
      gender: Gender.MALE,
      department: Department.MARKET_RESEARCH,
      employeeCode: "2102",
      isActive: true,
      dateOfJoining: new Date("2024-09-10"),
    },
    {
      firstName: "Yashshree",
      middleName: "",
      lastName: "Deshmukh",
      employeeCode: "2103",
      isActive: true,
      department: Department.MARKETING_SEO,
      gender: Gender.FEMALE,
      email: "yashshree@marksparksolutions.com",
      password: process.env.EMP_STARTER_PASS,
      dateOfJoining: new Date("2024-12-10"),
    },
    {
      firstName: "Mayur",
      middleName: "",
      lastName: "Wani",
      gender: Gender.MALE,
      employeeCode: "2105",
      isActive: true,
      department: Department.GRAPHIC_DESIGNER,
      dateOfJoining: new Date("2025-06-16"),
    },
    {
      firstName: "Arshdeep",
      middleName: "",
      lastName: "Kaur",
      employeeCode: "2123",
      gender: Gender.MALE,
      department: Department.MARKET_RESEARCH,
      isActive: true,
      dateOfJoining: new Date("2025-11-10"),
    },
    {
      firstName: "Pratiksha",
      middleName: "",
      lastName: "Yeole",
      employeeCode: "2124",
      gender: Gender.FEMALE,
      isActive: true,
      dateOfJoining: new Date("2025-06-02"),
    },
    {
      firstName: "Abhishek",
      middleName: "",
      lastName: "Ingole",
      gender: Gender.MALE,
      role: Role.INTERN,
      department: Department.MARKETING_SEO,
      employeeCode: "1003",
      isActive: true,
      dateOfJoining: new Date("2025-09-23"),
    },
    {
      firstName: "Pravan",
      middleName: "",
      lastName: "Kathawate",
      gender: Gender.MALE,
      role: Role.INTERN,
      department: Department.MARKETING_SEO,
      employeeCode: "1004",
      isActive: true,
      dateOfJoining: new Date("2025-09-22"),
    },
    {
      firstName: "Vidya",
      middleName: "",
      lastName: "Jaisingpure",
      employeeCode: "1002",
      role: Role.INTERN,
      department: Department.MARKETING_SEO,
      gender: Gender.FEMALE,
      isActive: true,
      dateOfJoining: new Date("2025-09-25"),
    },
    {
      firstName: "Pratik",
      middleName: "",
      lastName: "Sugandhi",
      gender: Gender.MALE,
      role: Role.INTERN,
      employeeCode: "1006",
      department: Department.MARKETING_SEO,
      isActive: true,
      dateOfJoining: new Date("2025-10-09"),
    },
    {
      firstName: "Ajinkya",
      middleName: "",
      lastName: "Wadekar",
      gender: Gender.MALE,
      role: Role.INTERN,
      employeeCode: "1007",
      department: Department.MARKETING_SEO,
      isActive: true,
      dateOfJoining: new Date("2025-11-05"),
    },
    {
      firstName: "Shubham",
      middleName: "",
      lastName: "Singh",
      gender: Gender.MALE,
      role: Role.INTERN,
      employeeCode: "1008",
      department: Department.MARKETING_SEO,
      isActive: true,
      dateOfJoining: new Date("2025-11-12"),
    },
    {
      firstName: "Ananias",
      middleName: "",
      lastName: "M",
      employeeCode: "2115",
      isActive: true,
      email: "ananias.m@itviadatasolutions.com",
      password: process.env.EMP_STARTER_PASS,
      dateOfJoining: new Date("2025-10-28"),
    },
    {
      firstName: "Neha",
      middleName: "",
      lastName: "Gavane",
      employeeCode: "2116",
      gender: Gender.FEMALE,
      isActive: true,
      email: "neha.gmarkandsparksolutions@gmail.com",
      password: process.env.EMP_STARTER_PASS,
      dateOfJoining: new Date("2025-10-31"),
    },
    {
      firstName: "Ashish",
      middleName: "",
      lastName: "Hiraskar",
      gender: Gender.MALE,
      department: Department.EMAIL_MARKETING,
      employeeCode: "2117",
      isActive: true,
      dateOfJoining: new Date("2025-10-31"),
    },
    {
      firstName: "Prasad",
      middleName: "",
      lastName: "Thokal",
      gender: Gender.MALE,
      employeeCode: "2118",
      isActive: true,
      dateOfJoining: new Date("2025-10-31"),
    },
    {
      firstName: "Aryan",
      middleName: "",
      lastName: "Bassi",
      gender: Gender.MALE,
      employeeCode: "2119",
      isActive: false,
      dateOfJoining: new Date("2025-11-03"),
    },
    {
      firstName: "Pratap",
      middleName: "",
      lastName: "Gaikwad",
      gender: Gender.MALE,
      employeeCode: "2120",
      isActive: false,
      dateOfJoining: new Date("2025-11-03"),
    },
    {
      firstName: "Siddesh",
      middleName: "",
      lastName: "Thorat",
      gender: Gender.MALE,
      employeeCode: "2121",
      isActive: false,
      dateOfJoining: new Date("2025-11-06"),
    },
    {
      firstName: "Abhilasha",
      middleName: "",
      lastName: "Dhanraj",
      employeeCode: "2122",
      gender: Gender.FEMALE,
      isActive: false,
      dateOfJoining: new Date("2025-11-13"),
    },
    {
      firstName: "Ieleen",
      middleName: "",
      lastName: "Marandi",
      employeeCode: "2004",
      role: Role.MANAGER,
      gender: Gender.FEMALE,
      department: Department.EMAIL_MARKETING,
      isActive: true,
      dateOfJoining: new Date("2018-09-21"),
    },
    {
      firstName: "Ambika",
      middleName: "Mallikarjun",
      lastName: "Sangolagi",
      employeeCode: "2070",
      gender: Gender.FEMALE,
      department: Department.EMAIL_MARKETING,
      isActive: true,
      dateOfJoining: new Date("2022-03-25"),
    },
  ];

  // Typed userRecords for safe lookup
  const userRecords: Record<string, User> = {};

  for (const user of usersData) {
    const key = getBestUserFullName(
      user.firstName,
      user.middleName,
      user.lastName
    );
    const email = getEmail(user);
    const { password, pin } = await getHashedCredentials(user);

    // 1️⃣ Create the User record
    const record = await prisma.user.create({
      data: {
        employeeCode: user.employeeCode,
        email,
        password,
        pin,
        role: user.role ?? Role.EMPLOYEE,
        isActive: user.isActive ?? false,
      },
    });

    // 2️⃣ Create the associated UserInfo record
    await prisma.userInfo.create({
      data: {
        userId: record.id,
        firstName: user.firstName,
        middleName: user.middleName || null,
        lastName: user.lastName,
        gender: user.gender || null,
        department: (user.department as Department) || null,
        dateOfJoining: user.dateOfJoining ?? new Date(),
        dateOfBirth: user.dateOfBirth ?? null,
      },
    });

    userRecords[key] = record;
  }

  console.log("✅ Seeded Users with manager roles assigned");

  const teamsData: TeamSeedData[] = [
    {
      name: "Back Office",
      managerKey: getBestUserFullName("Swati", "Shrikesh", "Tapkir"),
      additionalMembers: [
        "Deepali Pandurang Pashankar",
        "Manish Sampat Chaudhari",
        "Gayatri More",
        "Ashwini Shantaram Kamble",
      ],
    },
    {
      name: "Mark and Sparks",
      managerKey: getBestUserFullName("Sushil", "", "Waghmare"),
      additionalMembers: [
        "Sushil Waghmare",
        "Abhijith Nair",
        "Jayesh Mali",
        "Akash Patil",
        "Rutik Devade",
        "Sumit Ingle",
        "Yashshree Deshmukh",
        "Mayur Wani",
        "Arshdeep Kaur",
        "Pratiksha Yeole",
      ],
    },
    {
      name: "Mark and Sparks - Intern",
      additionalMembers: [
        "Abhishek Ingole",
        "Pravan Kathawate",
        "Vidya Jaisingpure",
        "Pratik Sugandhi ",
        "Ajinkya Wadekar",
        "Shubham Singh",
      ],
    },
    {
      name: "Appeals",
      managerKey: getBestUserFullName("Ieleen", "", "Marandi"),
      additionalMembers: ["Ananias M", "Neha Gavane"],
    },
  ];

  const teamRecords: Record<string, number> = {};

  // 1️⃣ Create all teams first
  for (const team of teamsData) {
    const managerId = team.managerKey
      ? userRecords[team.managerKey]?.id
      : undefined;

    if (team.managerKey && !managerId) {
      console.error(`❌ Manager not found for: ${team.name}`);
    }

    const createdTeam = await prisma.team.create({
      data: {
        name: team.name,
        managerId,
      },
    });

    teamRecords[team.name] = createdTeam.id;
  }

  // 2️⃣ Add managers as team members (EXACTLY ONCE)
  for (const team of teamsData) {
    if (!team.managerKey) continue;

    const managerId = userRecords[team.managerKey]?.id;
    const teamId = teamRecords[team.name];

    if (!managerId || !teamId) continue;

    await prisma.teamMember.upsert({
      where: {
        userId_teamId: { userId: managerId, teamId },
      },
      update: {},
      create: {
        userId: managerId,
        teamId: teamId,
        joinDate: new Date(),
      },
    });

    console.log(
      `👥 Added manager '${team.managerKey}' as member of team '${team.name}'`
    );

    if (team.additionalMembers) {
      for (const memberName of team.additionalMembers) {
        const memberId = userRecords[memberName];

        if (memberId && teamId) {
          await prisma.teamMember.upsert({
            where: {
              userId_teamId: { userId: memberId.id, teamId },
            },
            update: {},
            create: {
              userId: memberId.id,
              teamId: teamId,
              joinDate: new Date(),
            },
          });

          console.log(
            `👥 Added '${memberName}' as member of team '${team.name}'`
          );
        }
      }
    }
  }

  console.log("✅ Seeded Teams with specific managers");
  console.log("🎉 Seed Completed!");

  await seedAttendance(userRecords);
  await seedLeaveBalances(userRecords);

  console.log("🎉 Seed Completed!");
}

async function seedAttendance(userRecords: Record<string, User>) {
  console.log("⏳ Seeding Attendance for December 2025...");

  // This data is extracted from the provided "Holidays Dec.xlsx"
  const attendanceData = [
    {
      name: "Deepali Pandurang Pashankar",
      records: [
        { date: "2025-12-01", status: "PRESENT" },
        { date: "2025-12-02", status: "PRESENT" },
        { date: "2025-12-03", status: "PRESENT" },
        { date: "2025-12-04", status: "PRESENT" },
        { date: "2025-12-05", status: "PRESENT" },
        { date: "2025-12-06", status: "PRESENT" },
        { date: "2025-12-08", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-09", status: "PRESENT" },
        { date: "2025-12-10", status: "PRESENT" },
        { date: "2025-12-11", status: "PRESENT" },
        { date: "2025-12-12", status: "PRESENT" },
        { date: "2025-12-13", status: "PRESENT" },
        { date: "2025-12-15", status: "PRESENT" },
        { date: "2025-12-16", status: "PRESENT" },
        { date: "2025-12-17", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-18", status: "LEAVE_FULL_DAY" },
      ],
    },
    {
      name: "Manish Sampat Chaudhari",
      records: [
        { date: "2025-12-01", status: "PRESENT" },
        { date: "2025-12-02", status: "PRESENT" },
        { date: "2025-12-03", status: "PRESENT" },
        { date: "2025-12-04", status: "PRESENT" },
        { date: "2025-12-05", status: "PRESENT" },
        { date: "2025-12-06", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-08", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-09", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-10", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-11", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-12", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-13", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-15", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-16", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-17", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-18", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-19", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-20", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-22", status: "PRESENT" },
        { date: "2025-12-23", status: "PRESENT" },
        { date: "2025-12-24", status: "PRESENT" },
        { date: "2025-12-25", status: "HOLIDAY" },
        { date: "2025-12-26", status: "PRESENT" },
        { date: "2025-12-29", status: "PRESENT" },
        { date: "2025-12-30", status: "PRESENT" },
        { date: "2025-12-31", status: "PRESENT" },
      ],
    },
    {
      name: "Swati Shrikesh Tapkir",
      records: [
        { date: "2025-12-01", status: "LEAVE_HALF_DAY" },
        { date: "2025-12-02", status: "PRESENT" },
        { date: "2025-12-03", status: "PRESENT" },
        { date: "2025-12-04", status: "PRESENT" },
        { date: "2025-12-05", status: "PRESENT" },
        { date: "2025-12-06", status: "PRESENT" },
        { date: "2025-12-07", status: "PRESENT" },
        { date: "2025-12-08", status: "PRESENT" },
        { date: "2025-12-09", status: "PRESENT" },
        { date: "2025-12-10", status: "PRESENT" },
        { date: "2025-12-11", status: "PRESENT" },
        { date: "2025-12-12", status: "PRESENT" },
        { date: "2025-12-13", status: "PRESENT" },
        { date: "2025-12-15", status: "PRESENT" },
        { date: "2025-12-16", status: "PRESENT" },
        { date: "2025-12-17", status: "PRESENT" },
        { date: "2025-12-18", status: "PRESENT" },
        { date: "2025-12-19", status: "PRESENT" },
        { date: "2025-12-20", status: "PRESENT" },
        { date: "2025-12-22", status: "PRESENT" },
        { date: "2025-12-23", status: "PRESENT" },
        { date: "2025-12-24", status: "LEAVE_FULL_DAY" },
        { date: "2025-12-25", status: "HOLIDAY" },
        { date: "2025-12-29", status: "LEAVE_FULL_DAY" },
      ],
    },
  ];

  for (const emp of attendanceData) {
    const user = userRecords[emp.name];
    if (!user) {
      console.warn(`⚠️ User not found for attendance: ${emp.name}`);
      continue;
    }

    const records = emp.records.map((r) => ({
      userId: user.id,
      date: new Date(r.date),
      status: r.status as AttendanceStatus,
      halfDayPeriod:
        r.status === AttendanceStatus.LEAVE_HALF_DAY
          ? HalfDayPeriod.FIRST_HALF
          : null,
    }));

    await prisma.attendance.createMany({
      data: records,
      skipDuplicates: true,
    });
  }
  console.log("✅ Attendance seeded successfully.");
}

async function seedLeaveBalances(userRecords: Record<string, any>) {
  console.log("⏳ Seeding Leave Balances for December 2025...");

  const balances = [
    {
      name: "Deepali Pandurang Pashankar",
      data: {
        userId: 5,
        month: 12,
        year: 2025,
        earnedBalance: 0,
        used: 3.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 3.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: -0.75,
        initialBalance: 2.25,
        payableDays: 0.0,
      },
    },
    {
      name: "Manish Sampat Chaudhari",
      data: {
        userId: 6,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 13.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 13.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 2.0,
        initialBalance: 13.25,
        payableDays: 0.0,
      },
    },
    {
      name: "Swati Shrikesh Tapkir",
      data: {
        userId: 7,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 1.0,
        halfDayLeaves: 0.5,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 3.0,
        initialBalance: 2.75,
        payableDays: 0.0,
      },
    },
    {
      name: "Gayatri More",
      data: {
        userId: 8,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 1.0,
        halfDayLeaves: 0.5,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 2.5,
        initialBalance: 2.25,
        payableDays: 0.0,
      },
    },
    {
      name: "Ashwini Shantaram Kamble",
      data: {
        userId: 9,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 1.0,
        halfDayLeaves: 0.5,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 1,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 1.75,
        initialBalance: 2.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Sushil Waghmare",
      data: {
        userId: 10,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 2.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 2.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 18.0,
        initialBalance: 18.25,
        payableDays: 0.0,
      },
    },
    {
      name: "Abhijith Nair",
      data: {
        userId: 11,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 2.0,
        halfDayLeaves: 1.0,
        fullDayLeaves: 2.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 12,
        initialBalance: 12.75,
        payableDays: 0.0,
      },
    },
    {
      name: "Jayesh Mali",
      data: {
        userId: 12,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 2.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 2.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 6.5,
        initialBalance: 6.75,
        payableDays: 0.0,
      },
    },
    {
      name: "Akash Patil",
      data: {
        userId: 13,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 4.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 4.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 4.25,
        initialBalance: 6.5,
        payableDays: 0.0,
      },
    },
    {
      name: "Rutik Devade",
      data: {
        userId: 14,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 5.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 5.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 5.25,
        initialBalance: 8.5,
        payableDays: 0.0,
      },
    },
    {
      name: "Sumit Ingle",
      data: {
        userId: 15,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 1.0,
        halfDayLeaves: 1.0,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 3.0,
        initialBalance: 2.75,
        payableDays: 0.0,
      },
    },
    {
      name: "Yashshree Deshmukh",
      data: {
        userId: 16,
        month: 12,
        year: 2025,
        earnedBalance: 1.75,
        used: 1.0,
        halfDayLeaves: 1.0,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 4.25,
        initialBalance: 3.5,
        payableDays: 0.0,
      },
    },
    {
      name: "Mayur Wani",
      data: {
        userId: 17,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 3.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 3.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: -3.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Arshdeep Kaur",
      data: {
        userId: 18,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 3.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 3.0,
        finalBalance: 3.0,
        initialBalance: 3.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Pratiksha  Yeole",
      data: {
        userId: 19,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 3.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Ieleen Marandi",
      data: {
        userId: 34,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 1.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 3.0,
        finalBalance: -0.5,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Ambika Mallikarjun Sangolagi",
      data: {
        userId: 35,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 1.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 3.0,
        finalBalance: -0.1,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Ashish Hiraskar",
      data: {
        userId: 28,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Abhishek Ingole",
      data: {
        userId: 20,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 1.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Pravan Kathawate",
      data: {
        userId: 21,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Vidya Jaisingpure",
      data: {
        userId: 22,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 4.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Pratik Sugandhi",
      data: {
        userId: 23,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 3.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Ajinkya Wadekar",
      data: {
        userId: 24,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 1.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Shubham Singh",
      data: {
        userId: 25,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Ananias M",
      data: {
        userId: 26,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 3.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Neha Gavane",
      data: {
        userId: 27,
        month: 12,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Deepali Pandurang Pashankar",
      data: {
        userId: 5,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 6.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 6.0,
        leavesWithoutPay: 2.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 2.25,
        initialBalance: 6.5,
        payableDays: 0.0,
      },
    },
    {
      name: "Manish Sampat Chaudhari",
      data: {
        userId: 6,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 1.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 13.25,
        initialBalance: 12.5,
        payableDays: 0.0,
      },
    },
    {
      name: "Swati Shrikesh Tapkir",
      data: {
        userId: 7,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 3.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 3.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 2.75,
        initialBalance: 4.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Gayatri More",
      data: {
        userId: 8,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 1.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 2.25,
        initialBalance: 1.5,
        payableDays: 0.0,
      },
    },
    {
      name: "Ashwini Shantaram Kamble",
      data: {
        userId: 9,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 2.0,
        halfDayLeaves: 1.0,
        fullDayLeaves: 2.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 1.75,
        initialBalance: 2.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Sushil Waghmare",
      data: {
        userId: 10,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 20.0,
        initialBalance: 18.25,
        payableDays: 0.0,
      },
    },
    {
      name: "Abhijith Nair",
      data: {
        userId: 11,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 14.5,
        initialBalance: 12.75,
        payableDays: 0.0,
      },
    },
    {
      name: "Jayesh Mali",
      data: {
        userId: 12,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 8.5,
        initialBalance: 6.75,
        payableDays: 0.0,
      },
    },
    {
      name: "Akash Patil",
      data: {
        userId: 13,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 8.25,
        initialBalance: 6.5,
        payableDays: 0.0,
      },
    },
    {
      name: "Rutik Devade",
      data: {
        userId: 14,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 2.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 2.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 8.25,
        initialBalance: 8.5,
        payableDays: 0.0,
      },
    },
    {
      name: "Sumit Ingle",
      data: {
        userId: 15,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 2.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 3.5,
        initialBalance: 2.75,
        payableDays: 0.0,
      },
    },
    {
      name: "Yashshree Deshmukh",
      data: {
        userId: 16,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 3.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 3.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 2.25,
        initialBalance: 3.5,
        payableDays: 0.0,
      },
    },
    {
      name: "Mayur Wani",
      data: {
        userId: 17,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Arshdeep Kaur",
      data: {
        userId: 18,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Pratiksha  Yeole",
      data: {
        userId: 19,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 1.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: -0.5,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Ieleen Marandi",
      data: {
        userId: 34,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 1.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 1.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.75,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Ambika Mallikarjun Sangolagi",
      data: {
        userId: 35,
        month: 11,
        year: 2025,
        earnedBalance: 1.75,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 1.75,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Ashish Hiraskar",
      data: {
        userId: 28,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Abhishek Ingole",
      data: {
        userId: 20,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 1.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Pravan Kathawate",
      data: {
        userId: 21,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 1.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Vidya Jaisingpure",
      data: {
        userId: 22,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 7.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Pratik Sugandhi",
      data: {
        userId: 23,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 1.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Ajinkya Wadekar",
      data: {
        userId: 24,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 2.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Shubham Singh",
      data: {
        userId: 25,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 1.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Ananias M",
      data: {
        userId: 26,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Neha Gavane",
      data: {
        userId: 27,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Prasad Thokal",
      data: {
        userId: 29,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Aryan Bassi",
      data: {
        userId: 30,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
    {
      name: "Pratap Gaikwad",
      data: {
        userId: 31,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Siddesh Thorat",
      data: {
        userId: 32,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },

    {
      name: "Abhilasha Dhanraj",
      data: {
        userId: 33,
        month: 11,
        year: 2025,
        earnedBalance: 0.0,
        used: 0.0,
        halfDayLeaves: 0.0,
        fullDayLeaves: 0.0,
        leavesWithoutPay: 0.0,
        compOffsUsed: 0.0,
        workFromHome: 0.0,
        finalBalance: 0.0,
        initialBalance: 0.0,
        payableDays: 0.0,
      },
    },
  ];

  for (const item of balances) {
    const user = userRecords[item.name];
    if (user) {
      await prisma.leaveBalanceMonth.upsert({
        where: {
          userId_month_year: {
            userId: user.id,
            month: item.data.month,
            year: item.data.year,
          },
        },
        update: item.data,
        create: {
          ...item.data,
          userId: user.id,
        },
      });
    }
  }

  console.log("✅ Leave Balances seeded");
}

main()
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
